---
version: "3"

tasks:
  clean:
    cmds:
      - rm -f schemas.zip
      - rm -rf schemas
      - rm -rf vendor
      - rm -rf node_modules

  install:
    cmds:
      - npm install
      - jb install

  format:
    cmds:
      - jsonnetfmt -i --indent 2 --max-blank-lines 2 --sort-imports --string-style s --comment-style s ./1.0.0/**/*.libsonnet
      - jsonnetfmt -i --indent 2 --max-blank-lines 2 --sort-imports --string-style s --comment-style s ./1.0.0/AWS.libsonnet

  schemas-download:
    deps: [install]
    cmds:
      - wget https://schema.cloudformation.eu-central-1.amazonaws.com/CloudformationSchema.zip -O schemas.zip
      - unzip -o schemas.zip -d schemas

  generate:
    deps: ['schemas-download']
    cmds:
      - node .generator/index.js
      - task: format

...
