---
version: "3"

tasks:
  format:
    cmds:
#      - jsonnetfmt -i --indent 2 --max-blank-lines 2 --sort-imports --string-style s --comment-style s ./1.0.0/*.libsonnet
      - jsonnetfmt -i --indent 2 --max-blank-lines 2 --sort-imports --string-style s --comment-style s ./1.0.0/**/*.libsonnet

  schemas-download:
    cmds:
      - wget https://schema.cloudformation.eu-central-1.amazonaws.com/CloudformationSchema.zip -O schemas.zip
      - unzip -o schemas.zip -d schemas
      - rm -f schemas.zip

  generate:
    cmds:
      - node .generator/index.js
      - task: format
