{
  UserPoolUserToGroupAttachment: import 'UserPoolUserToGroupAttachment.libsonnet',
  UserPoolUser: import 'UserPoolUser.libsonnet',
  UserPoolUICustomizationAttachment: import 'UserPoolUICustomizationAttachment.libsonnet',
  UserPoolRiskConfigurationAttachment: import 'UserPoolRiskConfigurationAttachment.libsonnet',
  UserPoolResourceServer: import 'UserPoolResourceServer.libsonnet',
  UserPoolIdentityProvider: import 'UserPoolIdentityProvider.libsonnet',
  UserPoolGroup: import 'UserPoolGroup.libsonnet',
  UserPoolDomain: import 'UserPoolDomain.libsonnet',
  UserPoolClient: import 'UserPoolClient.libsonnet',
  UserPool: import 'UserPool.libsonnet',
  ManagedLoginBranding: import 'ManagedLoginBranding.libsonnet',
  LogDeliveryConfiguration: import 'LogDeliveryConfiguration.libsonnet',
  IdentityPoolRoleAttachment: import 'IdentityPoolRoleAttachment.libsonnet',
  IdentityPoolPrincipalTag: import 'IdentityPoolPrincipalTag.libsonnet',
  IdentityPool: import 'IdentityPool.libsonnet',
}
