{
  StreamingDistribution: import 'StreamingDistribution.libsonnet',
  ResponseHeadersPolicy: import 'ResponseHeadersPolicy.libsonnet',
  RealtimeLogConfig: import 'RealtimeLogConfig.libsonnet',
  PublicKey: import 'PublicKey.libsonnet',
  OriginRequestPolicy: import 'OriginRequestPolicy.libsonnet',
  OriginAccessControl: import 'OriginAccessControl.libsonnet',
  MonitoringSubscription: import 'MonitoringSubscription.libsonnet',
  KeyValueStore: import 'KeyValueStore.libsonnet',
  KeyGroup: import 'KeyGroup.libsonnet',
  Function: import 'Function.libsonnet',
  Distribution: import 'Distribution.libsonnet',
  ContinuousDeploymentPolicy: import 'ContinuousDeploymentPolicy.libsonnet',
  CloudFrontOriginAccessIdentity: import 'CloudFrontOriginAccessIdentity.libsonnet',
  CachePolicy: import 'CachePolicy.libsonnet',
}
