{
  OptionGroup: import 'OptionGroup.libsonnet',
  Integration: import 'Integration.libsonnet',
  GlobalCluster: import 'GlobalCluster.libsonnet',
  EventSubscription: import 'EventSubscription.libsonnet',
  DBSubnetGroup: import 'DBSubnetGroup.libsonnet',
  DBShardGroup: import 'DBShardGroup.libsonnet',
  DBSecurityGroupIngress: import 'DBSecurityGroupIngress.libsonnet',
  DBSecurityGroup: import 'DBSecurityGroup.libsonnet',
  DBProxyTargetGroup: import 'DBProxyTargetGroup.libsonnet',
  DBProxyEndpoint: import 'DBProxyEndpoint.libsonnet',
  DBProxy: import 'DBProxy.libsonnet',
  DBParameterGroup: import 'DBParameterGroup.libsonnet',
  DBInstance: import 'DBInstance.libsonnet',
  DBClusterParameterGroup: import 'DBClusterParameterGroup.libsonnet',
  DBCluster: import 'DBCluster.libsonnet',
  CustomDBEngineVersion: import 'CustomDBEngineVersion.libsonnet',
}
