{
  TagOptionAssociation: (import 'ServiceCatalog/TagOptionAssociation.libsonnet'),
  TagOption: (import 'ServiceCatalog/TagOption.libsonnet'),
  StackSetConstraint: (import 'ServiceCatalog/StackSetConstraint.libsonnet'),
  ServiceActionAssociation: (import 'ServiceCatalog/ServiceActionAssociation.libsonnet'),
  ServiceAction: (import 'ServiceCatalog/ServiceAction.libsonnet'),
  ResourceUpdateConstraint: (import 'ServiceCatalog/ResourceUpdateConstraint.libsonnet'),
  PortfolioShare: (import 'ServiceCatalog/PortfolioShare.libsonnet'),
  PortfolioProductAssociation: (import 'ServiceCatalog/PortfolioProductAssociation.libsonnet'),
  PortfolioPrincipalAssociation: (import 'ServiceCatalog/PortfolioPrincipalAssociation.libsonnet'),
  Portfolio: (import 'ServiceCatalog/Portfolio.libsonnet'),
  LaunchTemplateConstraint: (import 'ServiceCatalog/LaunchTemplateConstraint.libsonnet'),
  LaunchRoleConstraint: (import 'ServiceCatalog/LaunchRoleConstraint.libsonnet'),
  LaunchNotificationConstraint: (import 'ServiceCatalog/LaunchNotificationConstraint.libsonnet'),
  CloudFormationProvisionedProduct: (import 'ServiceCatalog/CloudFormationProvisionedProduct.libsonnet'),
  CloudFormationProduct: (import 'ServiceCatalog/CloudFormationProduct.libsonnet'),
  AcceptedPortfolioShare: (import 'ServiceCatalog/AcceptedPortfolioShare.libsonnet'),
}
